MarketKasaSistemi.Web/Areas/Yonetim/Controllers/KategorilerController.cs
using MarketKasaSistemi.DataAccess;
using MarketKasaSistemi.Entities;
using MarketKasaSistemi.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarketKasaSistemi.Web.Areas.Yonetim.Controllers
{
    public class KategorilerController : Controller
    {
        [GirisKontrol]
        public ActionResult Index()
        {
            using (UnitOfWork uow = new UnitOfWork())
                return View(uow.KategoriRepository.ToList());
        }
        [GirisKontrol]
        public ActionResult Ekle()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken,GirisKontrol]
        public ActionResult Ekle(Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.KategoriRepository.Add(kategori);
                    return RedirectToAction("Index");
                }
            }
            return View(kategori);
        }

        [GirisKontrol]
        public ActionResult Duzenle(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Kategori kategori = uow.KategoriRepository.GetItem(id);
                    if (kategori != null)
                        return View(kategori);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryToken,GirisKontrol]
        public ActionResult Duzenle(int? id, Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.KategoriRepository.Update(kategori);
                    return RedirectToAction("Index");
                }
            }
            return View(kategori);
        }
        [GirisKontrol]
        public ActionResult Sil(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Kategori kategori = uow.KategoriRepository.GetItem(id);
                    if (kategori != null)
                        return View(kategori);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpPost, ValidateAntiForgeryToken, ActionName("Sil"),GirisKontrol]
        public ActionResult SilOnay(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Kategori kategori = uow.KategoriRepository.GetItem(id);
                    if (kategori != null)
                    {
                        uow.KategoriRepository.Remove(kategori);
                        return RedirectToAction("Index");
                    }
                }
            }
            return RedirectToAction("Index");
        }
    }
}

MarketKasaSistemi.Web/Areas/Yonetim/Controllers/KullanicilarController.cs
using MarketKasaSistemi.DataAccess;
using MarketKasaSistemi.Entities;
using MarketKasaSistemi.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarketKasaSistemi.Web.Areas.Yonetim.Controllers
{
    public class KullanicilarController : Controller
    {
        [GirisKontrol]
        public ActionResult Index()
        {
            using (UnitOfWork uow = new UnitOfWork())
                return View(uow.KullaniciRepository.ToList());
        }

        [GirisKontrol]
        public ActionResult Duzenle(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Kullanici kullanici = uow.KullaniciRepository.GetItem(id);
                    if (kullanici != null)
                        return View(kullanici);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryToken, GirisKontrol]
        public ActionResult Duzenle(int? id, Kullanici kullanici)
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                Kullanici updateUser = uow.KullaniciRepository.GetItem(kullanici.Id);
                Kullanici aktif = HttpContext.Session["User"] as Kullanici;
                updateUser.KullaniciAd = kullanici.KullaniciAd;
                updateUser.KullaniciSifre = kullanici.KullaniciSifre;
                if (kullanici != null)
                {
                    if (ModelState.IsValid)
                    {
                        uow.KullaniciRepository.Update(updateUser);
                        if(kullanici.Id == aktif.Id)
                            Session["User"] = null;
                        return RedirectToAction("Index");
                    }
                }
                ModelState.AddModelError("", "Bir Hata Oluştu");
                return View(updateUser);
            }
        }
        [GirisKontrol]
        public ActionResult Sil(int? id)
        {
            Kullanici aktif = HttpContext.Session["User"] as Kullanici;
            if (id != null && id != aktif.Id)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Kullanici kullanici = uow.KullaniciRepository.GetItem(id);
                    if (kullanici != null)
                        return View(kullanici);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpPost, ValidateAntiForgeryToken, ActionName("Sil"), GirisKontrol]
        public ActionResult SilOnay(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Kullanici kullanici = uow.KullaniciRepository.GetItem(id);
                    if (kullanici != null)
                    {
                        uow.KullaniciRepository.Remove(kullanici);
                        return RedirectToAction("Index");
                    }
                }
            }
            return RedirectToAction("Index");
        }
    }
}

MarketKasaSistemi.Web/Areas/Yonetim/Controllers/PersonellerController.cs
using MarketKasaSistemi.DataAccess;
using MarketKasaSistemi.Entities;
using MarketKasaSistemi.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarketKasaSistemi.Web.Areas.Yonetim.Controllers
{
    public class PersonellerController : Controller
    {
        [GirisKontrol]
        public ActionResult Index()
        {
            using (UnitOfWork uow = new UnitOfWork())
                return View(uow.PersonelRepository.ToList());
        }
        [GirisKontrol]
        public ActionResult Ekle()
        {
            using (UnitOfWork uow = new UnitOfWork())
                ViewBag.PersonelTip = new SelectList(uow.PersonelTipRepository.ToList(),"Id", "PersonelTipAd");
                return View();
        }
        [HttpPost, ValidateAntiForgeryToken, GirisKontrol]
        public ActionResult Ekle(Personel personel)
        {
            if (ModelState.IsValid)
            {
                personel.PersonelBaslangicTarih = DateTime.Now;
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.PersonelRepository.Add(personel);
                    return RedirectToAction("Index");
                }
            }
            return View(personel);
        }
        [GirisKontrol]
        public ActionResult Duzenle(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Personel personel = uow.PersonelRepository.GetItem(id);
                    ViewBag.PersonelTip = new SelectList(uow.PersonelTipRepository.ToList(),"Id", "PersonelTipAd");
                    if (personel != null)
                        return View(personel);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryToken, GirisKontrol]
        public ActionResult Duzenle(int? id, Personel personel)
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                Kullanici aktif = HttpContext.Session["User"] as Kullanici;
                Personel updatePersonel = uow.PersonelRepository.GetItem(personel.Id);
                updatePersonel.PersonelAd = personel.PersonelAd;
                updatePersonel.PersonelSoyad = personel.PersonelSoyad;
                updatePersonel.PersonelTip = personel.PersonelTip;
                if (personel != null)
                {
                    if (ModelState.IsValid)
                    {
                        uow.PersonelRepository.Update(updatePersonel);
                        if (updatePersonel.Id == aktif.Personel.Id)
                            Session["User"] = null;
                        return RedirectToAction("Index");
                    }
                }
                ModelState.AddModelError("", "Bir Hata Oluştu");
                return View(updatePersonel);
            }
        }
        [GirisKontrol]
        public ActionResult Sil(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Personel personel = uow.PersonelRepository.GetItem(id);
                    if (personel != null)
                        return View(personel);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpPost, ValidateAntiForgeryToken, ActionName("Sil"), GirisKontrol]
        public ActionResult SilOnay(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Kullanici aktif = HttpContext.Session["User"] as Kullanici;
                    Personel personel = uow.PersonelRepository.GetItem(id);
                    List<Kullanici> kullanicilar = uow.KullaniciRepository.ToList();
                        if (kullanicilar.FirstOrDefault(x => x.Personel.Id == personel.Id) != null)
                            uow.KullaniciRepository.Remove(kullanicilar.FirstOrDefault(x => x.Personel.Id == personel.Id));
                    if (personel != null)
                    {
                        uow.PersonelRepository.Remove(personel);
                        if (personel.Id == aktif.Personel.Id)
                            Session["User"] = null;
                        return RedirectToAction("Index");
                    }
                }
            }
            return RedirectToAction("Index");
        }
    }
}

MarketKasaSistemi.Web/Areas/Yonetim/Controllers/UrunlerController.cs
using MarketKasaSistemi.DataAccess;
using MarketKasaSistemi.Entities;
using MarketKasaSistemi.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarketKasaSistemi.Web.Areas.Yonetim.Controllers
{
    public class UrunlerController : Controller
    {
        [GirisKontrol]
        public ActionResult Index()
        {
            using (UnitOfWork uow = new UnitOfWork())
                return View(uow.UrunRepository.ToList());
        }
        [GirisKontrol]
        public ActionResult Ekle()
        {
            using (UnitOfWork uow = new UnitOfWork()) {
                ViewBag.Kategoriler = new SelectList(uow.KategoriRepository.ToList(), "Id", "KategoriAd");
                ViewBag.Vergiler = new SelectList(uow.VergiRepository.ToList(),"Id","VergiMiktar");
            }
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken, GirisKontrol]
        public ActionResult Ekle(Urun urun)
        {
            if (ModelState.IsValid)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.UrunRepository.Add(urun);
                    return RedirectToAction("Index");
                }
            }
            return View(urun);
        }
        [GirisKontrol]
        public ActionResult Duzenle(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Urun urun = uow.UrunRepository.GetItem(id);
                    ViewBag.Kategoriler = new SelectList(uow.KategoriRepository.ToList(), "Id", "KategoriAd");
                    ViewBag.Vergiler = new SelectList(uow.VergiRepository.ToList(), "Id", "VergiMiktar");
                    if (urun != null)
                        return View(urun);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryToken, GirisKontrol]
        public ActionResult Duzenle(int? id, Urun urun)
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                Urun updateUrun = uow.UrunRepository.GetItem(urun.Id);
                updateUrun.UrunAd = urun.UrunAd;
                updateUrun.UrunFiyat = urun.UrunFiyat;
                updateUrun.UrunStokAdet = urun.UrunStokAdet;
                updateUrun.Kategori.Id = urun.Kategori.Id;
                updateUrun.Vergi.Id = urun.Vergi.Id;
                if (urun != null)
                {
                    if (ModelState.IsValid)
                    {
                        uow.UrunRepository.Update(updateUrun);
                        return RedirectToAction("Index");
                    }
                }
                ModelState.AddModelError("", "Bir Hata Oluştu");
                return View(updateUrun);
            }
        }
        [GirisKontrol]
        public ActionResult Sil(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Urun urun = uow.UrunRepository.GetItem(id);
                    if (urun != null)
                        return View(urun);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpPost, ValidateAntiForgeryToken, ActionName("Sil"), GirisKontrol]
        public ActionResult SilOnay(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Urun urun = uow.UrunRepository.GetItem(id);
                    if (urun != null)
                    {
                        uow.UrunRepository.Remove(urun);
                        return RedirectToAction("Index");
                    }
                }
            }
            return RedirectToAction("Index");
        }
    }
}

MarketKasaSistemi.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using MarketKasaSistemi.Entities
@{
    Kullanici giris = HttpContext.Current.Session["User"] as Kullanici;
        }
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/bundles/css")
</head>
<body class="light" id="bodyContain">
    <nav class="col-12 col-md-5 col-lg-4 max-height position-absolute drawerClose bg-prm" id="drawer">
        <div class="col-12 fs-1 p-3 white">
            <i class="fa fa-moon-o pointer" id="moon"></i>
            <i class="fa fa-lightbulb-o d-none pointer" id="bulb"></i>
            <i class="fa fa-arrow-left text-end float-end mt-2 mx-3 pointer" id="drawerArrow"></i>
        </div>
        <div class="col-12 text-center fw-bold white">
            <h2>@giris.Personel.PersonelAd @giris.Personel.PersonelSoyad</h2>
            <h4>@giris.Personel.PersonelTip.PersonelTipAd</h4>
        </div>
        <div class="col-12 fs-2 mt-5">
            <a href="~/Home/Satis" class="d-block menu-item"><i class="fa fa-cart-plus col-1 ms-2"></i> SATIŞ</a>
            <a href="~/Home/Barkod" class="d-block menu-item"><i class="fa fa-search col-1 ms-2"></i> BARKOD</a>
            <a href="~/Home/IadeEt" class="d-block menu-item"><i class="fa fa-money col-1 ms-2"></i> İADE ET</a>
            <a href="~/Home/ZRaporu" class="d-block menu-item"><i class="fa fa-file-text col-1 ms-2"></i> Z RAPORU</a>
            @if(giris.Personel.PersonelTip.Id == 1) { 
            <a href="#" class="d-block menu-item" id="dropMyLinks"><i class="fa fa-cogs col-1 ms-2"></i> YÖNETİCİ MENÜSÜ</a>
            <div id="dropLinks" class="d-none">
                <a href="@Url.Action("Index", "Kullanicilar", new {Area = "Yonetim"})" class="d-block menu-item fs-4"><i class="fa fa-dot-circle-o col-1 ms-4"></i> KULLANICILAR</a>
                <a href="@Url.Action("Index","Personeller",new {Area = "Yonetim"})" class="d-block menu-item fs-4"><i class="fa fa-dot-circle-o col-1 ms-4"></i> PERSONELLER</a>
                <a href="@Url.Action("Index","Urunler",new {Area = "Yonetim"})" class="d-block menu-item fs-4"><i class="fa fa-dot-circle-o col-1 ms-4"></i> ÜRÜNLER</a>
                <a href="@Url.Action("Index","Kategoriler",new {Area = "Yonetim"})" class="d-block menu-item fs-4"><i class="fa fa-dot-circle-o col-1 ms-4"></i> KATEGORİLER</a>
            </div>
            }
            <a href="~/Login/Logout" class="d-block menu-item position-absolute bottom-0 w-100 text-center"><i class="fa fa-sign-out col-1 ms-2"></i> ÇIKIŞ YAP</a>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="col-12 fs-1 prm-one">
            <i class="fa fa-bars col-1 d-inline text-center pointer" id="drawerBurger"></i>
            <h1 class="col-4 col-sm-11 offset-4 offset-sm-0 text-sm-center d-inline-block text-uppercase">@ViewBag.Title</h1>
        </div>
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/js")
</body>
</html>

MarketKasaSistemi.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/SEO.min.css" rel="stylesheet" />
</head>
<body class="light">
    <div class="container-fluid">
        @RenderBody()
    </div>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
</body>
</html>